displayName=Chrono Continued
author=rxmsey
support=https://github.com/rxmsey/chrono-continued/issues
description=Restrict your account by historical RuneScape release through the 10 August 2007 backup
tags=chrono,history,release,2007,restricted,oldschool
plugins=com.chrono.ChronoPlugin
version=
build=standard
