displayName=Rewind
author=rxmsey
support=https://github.com/rxmsey/rewind/issues
description=Experience Old School RuneScape through its historical timeline.
tags=rewind,history,release,2007,restricted,oldschool
plugins=com.rewind.RewindPlugin
version=
build=standard
