displayName=Chrono Continued
author=rxmsey
description=Restrict your account by historical RuneScape release through 10 August 2007
tags=chrono,history,release,2007,restricted,oldschool
plugins=com.chrono.ChronoPlugin
version=
build=standard
