package com.chrono;

import lombok.Getter;
import net.runelite.api.gameval.InterfaceID;

@Getter
public enum ChronoSpell {
    LUMBRIDGE_HOME_TELEPORT("Lumbridge Home Teleport",  InterfaceID.MagicSpellbook.TELEPORT_HOME_STANDARD, 356, 406),
    WIND_STRIKE("Wind Strike",                          InterfaceID.MagicSpellbook.WIND_STRIKE, 15,65),
    CONFUSE("Confuse",                                  InterfaceID.MagicSpellbook.CONFUSE, 16, 66),
    ENCHANT_CROSSBOW_BOLT("Enchant Crossbow Bolt",      InterfaceID.MagicSpellbook.XBOWS_ENCHANT, 358, 408),
    WATER_STRIKE("Water Strike",                        InterfaceID.MagicSpellbook.WATER_STRIKE, 17,67),
    LVL_1_ENCHANT("Lvl-1 Enchant",                      InterfaceID.MagicSpellbook.ENCHANT_1, 18, 68),
    EARTH_STRIKE("Earth Strike",                        InterfaceID.MagicSpellbook.EARTH_STRIKE, 19, 69),
    WEAKEN("Weaken",                                    InterfaceID.MagicSpellbook.WEAKEN, 20, 70),
    FIRE_STRIKE("Fire Strike",                          InterfaceID.MagicSpellbook.FIRE_STRIKE, 21, 71),
    BONES_TO_BANANAS("Bones to Bananas", InterfaceID.MagicSpellbook.BONES_BANANAS, 22, 72),
    WIND_BOLT("Wind Bolt", InterfaceID.MagicSpellbook.WIND_BOLT, 23, 73),
    CURSE("Curse", InterfaceID.MagicSpellbook.CURSE, 24, 74),
    BIND("Bind", InterfaceID.MagicSpellbook.BIND, 319, 369),
    LOW_LEVEL_ALCHEMY("Low Level Alchemy", InterfaceID.MagicSpellbook.LOW_ALCHEMY, 25, 75),
    WATER_BOLT("Water Bolt", InterfaceID.MagicSpellbook.WATER_BOLT, 26, 76),
    VARROCK_TELEPORT("Varrock Teleport", InterfaceID.MagicSpellbook.VARROCK_TELEPORT, 27, 77),
    LVL_2_ENCHANT("Lvl-2 Enchant", InterfaceID.MagicSpellbook.ENCHANT_2, 28, 78),
    EARTH_BOLT("Earth Bolt", InterfaceID.MagicSpellbook.EARTH_BOLT, 29, 79),
    LUMBRIDGE_TELEPORT("Lumbridge Teleport", InterfaceID.MagicSpellbook.LUMBRIDGE_TELEPORT, 30, 80),
    TELEKINETIC_GRAB("Telekinetic Grab", InterfaceID.MagicSpellbook.TELEGRAB, 31, 81),
    FIRE_BOLT("Fire Bolt", InterfaceID.MagicSpellbook.FIRE_BOLT, 32, 82),
    FALADOR_TELEPORT("Falador Teleport", InterfaceID.MagicSpellbook.FALADOR_TELEPORT, 33, 83),
    CRUMBLE_UNDEAD("Crumble Undead", InterfaceID.MagicSpellbook.CRUMBLE_UNDEAD, 34, 84),
    TELEPORT_TO_HOUSE("Teleport to House", InterfaceID.MagicSpellbook.TELEPORT_TO_YOUR_HOUSE, 355, 405),
    WIND_BLAST("Wind Blast", InterfaceID.MagicSpellbook.WIND_BLAST, 35, 85),
    SUPERHEAT_ITEM("Superheat Item", InterfaceID.MagicSpellbook.SUPERHEAT, 36, 86),
    CAMELOT_TELEPORT("Camelot Teleport", InterfaceID.MagicSpellbook.CAMELOT_TELEPORT, 37, 87),
    WATER_BLAST("Water Blast", InterfaceID.MagicSpellbook.WATER_BLAST, 38, 88),
    LVL_3_ENCHANT("Lvl-3 Enchant", InterfaceID.MagicSpellbook.ENCHANT_3, 39, 89),
    IBAN_BLAST("Iban Blast", InterfaceID.MagicSpellbook.IBAN_BLAST, 53, 103),
    SNARE("Snare", InterfaceID.MagicSpellbook.SNARE, 320, 370),
    MAGIC_DART("Magic Dart", InterfaceID.MagicSpellbook.MAGIC_DART, 324, 374),
    ARDOUGNE_TELEPORT("Ardougne Teleport", InterfaceID.MagicSpellbook.ARDOUGNE_TELEPORT, 54, 104),
    EARTH_BLAST("Earth Blast", InterfaceID.MagicSpellbook.EARTH_BLAST, 40, 90),
    HIGH_LEVEL_ALCHEMY("High Level Alchemy", InterfaceID.MagicSpellbook.HIGH_ALCHEMY, 41, 91),
    CHARGE_WATER_ORB("Charge Water Orb", InterfaceID.MagicSpellbook.CHARGE_WATER_ORB, 42, 92),
    LVL_4_ENCHANT("Lvl-4 Enchant", InterfaceID.MagicSpellbook.ENCHANT_4, 43, 93),
    WATCHTOWER_TELEPORT("Watchtower Teleport", InterfaceID.MagicSpellbook.WATCHTOWER_TELEPORT, 55, 105),
    FIRE_BLAST("Fire Blast", InterfaceID.MagicSpellbook.FIRE_BLAST, 44, 94),
    CHARGE_EARTH_ORB("Charge Earth Orb", InterfaceID.MagicSpellbook.CHARGE_EARTH_ORB, 45, 95),
    BONES_TO_PEACHES("Bones to Peaches", InterfaceID.MagicSpellbook.BONES_PEACHES, 354, 404),
    SARADOMIN_STRIKE("Saradomin Strike", InterfaceID.MagicSpellbook.SARADOMIN_STRIKE, 61, 111),
    FLAMES_OF_ZAMORAK("Flames of Zamorak", InterfaceID.MagicSpellbook.FLAMES_OF_ZAMORAK, 60, 110),
    CLAWS_OF_GUTHIX("Claws of Guthix", InterfaceID.MagicSpellbook.CLAWS_OF_GUTHIX, 59, 109),
    TROLLHEIM_TELEPORT("Trollheim Teleport", InterfaceID.MagicSpellbook.TROLLHEIM_TELEPORT, 323, 373),
    WIND_WAVE("Wind Wave", InterfaceID.MagicSpellbook.WIND_WAVE, 46, 96),
    CHARGE_FIRE_ORB("Charge Fire Orb", InterfaceID.MagicSpellbook.CHARGE_FIRE_ORB, 47, 97),
    APE_ATOLL_TELEPORT("Ape Atoll Teleport", InterfaceID.MagicSpellbook.APE_TELEPORT, 357, 407),
    WATER_WAVE("Water Wave", InterfaceID.MagicSpellbook.WATER_WAVE, 48, 98),
    CHARGE_AIR_ORB("Charge Air Orb", InterfaceID.MagicSpellbook.CHARGE_AIR_ORB, 49, 99),
    VULNERABILITY("Vulnerability", InterfaceID.MagicSpellbook.VULNERABILITY, 56, 106),
    LVL_5_ENCHANT("Lvl-5 Enchant", InterfaceID.MagicSpellbook.ENCHANT_5, 50, 100),
    KOUREND_CASTLE_TELEPORT("Kourend Castle Teleport", InterfaceID.MagicSpellbook.KOUREND_TELEPORT, 360, 410),
    EARTH_WAVE("Earth Wave", InterfaceID.MagicSpellbook.EARTH_WAVE, 51, 101),
    ENFEEBLE("Enfeeble", InterfaceID.MagicSpellbook.ENFEEBLE, 57, 107),
    TELEOTHER_LUMBRIDGE("Teleother Lumbridge", InterfaceID.MagicSpellbook.TELEOTHER_LUMBRIDGE, 349, 399),
    FIRE_WAVE("Fire Wave", InterfaceID.MagicSpellbook.FIRE_WAVE, 52, 102),
    ENTANGLE("Entangle", InterfaceID.MagicSpellbook.ENTANGLE, 321, 371),
    STUN("Stun", InterfaceID.MagicSpellbook.STUN, 58, 108),
    CHARGE("Charge", InterfaceID.MagicSpellbook.CHARGE, 322, 372),
    WIND_SURGE("Wind Surge", InterfaceID.MagicSpellbook.WIND_SURGE, 362, 412),
    TELEOTHER_FALADOR("Teleother Falador", InterfaceID.MagicSpellbook.TELEOTHER_FALADOR, 350, 400),
    WATER_SURGE("Water Surge", InterfaceID.MagicSpellbook.WATER_SURGE, 363, 413),
    TELE_BLOCK("Tele Block", InterfaceID.MagicSpellbook.TELEPORT_BLOCK, 352, 402),
    TELEPORT_TO_TARGET("Teleport to Target", InterfaceID.MagicSpellbook.BOUNTY_TARGET, 359, 409),
    LVL_6_ENCHANT("Lvl-6 Enchant", InterfaceID.MagicSpellbook.ENCHANT_6, 353, 403),
    TELEOTHER_CAMELOT("Teleother Camelot", InterfaceID.MagicSpellbook.TELEOTHER_CAMELOT, 351, 401),
    EARTH_SURGE("Earth Surge", InterfaceID.MagicSpellbook.EARTH_SURGE, 364, 414),
    LVL_7_ENCHANT("Lvl-7 Enchant", InterfaceID.MagicSpellbook.ENCHANT_7, 361, 411),
    FIRE_SURGE("Fire Surge", InterfaceID.MagicSpellbook.FIRE_SURGE, 365, 415),
    SMOKE_RUSH("Smoke Rush", InterfaceID.MagicSpellbook.SMOKE_RUSH, -1, -1),
    SMOKE_BURST("Smoke Burst", InterfaceID.MagicSpellbook.SMOKE_BURST, -1, -1),
    SMOKE_BLITZ("Smoke Blitz", InterfaceID.MagicSpellbook.SMOKE_BLITZ, -1, -1),
    SMOKE_BARRAGE("Smoke Barrage", InterfaceID.MagicSpellbook.SMOKE_BARRAGE, -1, -1),
    SHADOW_RUSH("Shadow Rush", InterfaceID.MagicSpellbook.SHADOW_RUSH, -1, -1),
    SHADOW_BURST("Shadow Burst", InterfaceID.MagicSpellbook.SHADOW_BURST, -1, -1),
    SHADOW_BLITZ("Shadow Blitz", InterfaceID.MagicSpellbook.SHADOW_BLITZ, -1, -1),
    SHADOW_BARRAGE("Shadow Barrage", InterfaceID.MagicSpellbook.SHADOW_BARRAGE, -1, -1),
    BLOOD_RUSH("Blood Rush", InterfaceID.MagicSpellbook.BLOOD_RUSH, -1, -1),
    BLOOD_BURST("Blood Burst", InterfaceID.MagicSpellbook.BLOOD_BURST, -1, -1),
    BLOOD_BLITZ("Blood Blitz", InterfaceID.MagicSpellbook.BLOOD_BLITZ, -1, -1),
    BLOOD_BARRAGE("Blood Barrage", InterfaceID.MagicSpellbook.BLOOD_BARRAGE, -1, -1),
    ICE_RUSH("Ice Rush", InterfaceID.MagicSpellbook.ICE_RUSH, -1, -1),
    ICE_BURST("Ice Burst", InterfaceID.MagicSpellbook.ICE_BURST, -1, -1),
    ICE_BLITZ("Ice Blitz", InterfaceID.MagicSpellbook.ICE_BLITZ, -1, -1),
    ICE_BARRAGE("Ice Barrage", InterfaceID.MagicSpellbook.ICE_BARRAGE, -1, -1),
    PADDEWWA_TELEPORT("Paddewwa Teleport", InterfaceID.MagicSpellbook.ZAROSTELEPORT1, -1, -1),
    SENNTISTEN_TELEPORT("Senntisten Teleport", InterfaceID.MagicSpellbook.ZAROSTELEPORT2, -1, -1),
    KHARYRLL_TELEPORT("Kharyrll Teleport", InterfaceID.MagicSpellbook.ZAROSTELEPORT3, -1, -1),
    LASSAR_TELEPORT("Lassar Teleport", InterfaceID.MagicSpellbook.ZAROSTELEPORT4, -1, -1),
    DAREEYAK_TELEPORT("Dareeyak Teleport", InterfaceID.MagicSpellbook.ZAROSTELEPORT5, -1, -1),
    CARRALLANGAR_TELEPORT("Carrallangar Teleport", InterfaceID.MagicSpellbook.ZAROSTELEPORT6, -1, -1),
    ANNAKARL_TELEPORT("Annakarl Teleport", InterfaceID.MagicSpellbook.ZAROSTELEPORT7, -1, -1),
    GHORROCK_TELEPORT("Ghorrock Teleport", InterfaceID.MagicSpellbook.ZAROSTELEPORT8, -1, -1),
    BAKE_PIE("Bake Pie", InterfaceID.MagicSpellbook.BAKE_PIE, -1, -1),
    CURE_PLANT("Cure Plant", InterfaceID.MagicSpellbook.CURE_PLANT, -1, -1),
    NPC_CONTACT("NPC Contact", InterfaceID.MagicSpellbook.NPC_CONTACT, -1, -1),
    CURE_OTHER("Cure Other", InterfaceID.MagicSpellbook.CURE_OTHER, -1, -1),
    CURE_ME("Cure Me", InterfaceID.MagicSpellbook.CURE_ME, -1, -1),
    CURE_GROUP("Cure Group", InterfaceID.MagicSpellbook.CURE_GROUP, -1, -1),
    SUPERGLASS_MAKE("Superglass Make", InterfaceID.MagicSpellbook.SUPERGLASS, -1, -1),
    STRING_JEWELLERY("String Jewellery", InterfaceID.MagicSpellbook.STRING_JEWEL, -1, -1),
    STAT_RESTORE_POT_SHARE("Stat Restore Pot Share", InterfaceID.MagicSpellbook.REST_POT_SHARE, -1, -1),
    MAGIC_IMBUE("Magic Imbue", InterfaceID.MagicSpellbook.MAGIC_IMBUE, -1, -1),
    FERTILE_SOIL("Fertile Soil", InterfaceID.MagicSpellbook.FERTILE_SOIL, -1, -1),
    BOOST_POTION_SHARE("Boost Potion Share", InterfaceID.MagicSpellbook.STREN_POT_SHARE, -1, -1),
    ENERGY_TRANSFER("Energy Transfer", InterfaceID.MagicSpellbook.ENERGY_TRANS, -1, -1),
    HEAL_OTHER("Heal Other", InterfaceID.MagicSpellbook.HEAL_OTHER, -1, -1),
    VENGEANCE_OTHER("Vengeance Other", InterfaceID.MagicSpellbook.VENGEANCE_OTHER, -1, -1),
    VENGEANCE("Vengeance", InterfaceID.MagicSpellbook.VENGEANCE, -1, -1),
    HEAL_GROUP("Heal Group", InterfaceID.MagicSpellbook.HEAL_GROUP, -1, -1),
    MOONCLAN_TELEPORT("Moonclan Teleport", InterfaceID.MagicSpellbook.TELE_MOONCLAN, -1, -1),
    TELE_GROUP_MOONCLAN("Tele Group Moonclan", InterfaceID.MagicSpellbook.TELE_GROUP_MOONCLAN, -1, -1),
    WATERBIRTH_TELEPORT("Waterbirth Teleport", InterfaceID.MagicSpellbook.TELE_WATERBIRTH, -1, -1),
    TELE_GROUP_WATERBIRTH("Tele Group Waterbirth", InterfaceID.MagicSpellbook.TELE_GROUP_WATERBIRTH, -1, -1),
    BARBARIAN_TELEPORT("Barbarian Teleport", InterfaceID.MagicSpellbook.TELE_BARB_OUT, -1, -1),
    TELE_GROUP_BARBARIAN("Tele Group Barbarian", InterfaceID.MagicSpellbook.TELE_GROUP_BARBARIAN, -1, -1),
    KHAZARD_TELEPORT("Khazard Teleport", InterfaceID.MagicSpellbook.TELE_KHAZARD, -1, -1),
    TELE_GROUP_KHAZARD("Tele Group Khazard", InterfaceID.MagicSpellbook.TELE_GROUP_KHAZARD, -1, -1),
    FISHING_GUILD_TELEPORT("Fishing Guild Teleport", InterfaceID.MagicSpellbook.TELE_FISH, -1, -1),
    TELE_GROUP_FISHING_GUILD("Tele Group Fishing Guild", InterfaceID.MagicSpellbook.TELE_GROUP_FISHING_GUILD, -1, -1),
    CATHERBY_TELEPORT("Catherby Teleport", InterfaceID.MagicSpellbook.TELE_CATHER, -1, -1),
    TELE_GROUP_CATHERBY("Tele Group Catherby", InterfaceID.MagicSpellbook.TELE_GROUP_CATHERBY, -1, -1),
    ICE_PLATEAU_TELEPORT("Ice Plateau Teleport", InterfaceID.MagicSpellbook.TELE_GHORROCK, -1, -1),
    TELE_GROUP_ICE_PLATEAU("Tele Group Ice Plateau", InterfaceID.MagicSpellbook.TELE_GROUP_GHORROCK, -1, -1),
    MONSTER_EXAMINE("Monster Examine", InterfaceID.MagicSpellbook.MONSTER_EXAMINE, -1, -1),
    HUMIDIFY("Humidify", InterfaceID.MagicSpellbook.HUMIDIFY, -1, -1),
    HUNTER_KIT("Hunter Kit", InterfaceID.MagicSpellbook.HUNTER_KIT, -1, -1),
    STAT_SPY("Stat Spy", InterfaceID.MagicSpellbook.STAT_SPY, -1, -1),
    DREAM("Dream", InterfaceID.MagicSpellbook.DREAM, -1, -1),
    PLANK_MAKE("Plank Make", InterfaceID.MagicSpellbook.PLANK_MAKE, -1, -1),
    SPELLBOOK_SWAP("Spellbook Swap", InterfaceID.MagicSpellbook.SPELLBOOK_SWAP, -1, -1),
    EDGEVILLE_HOME_TELEPORT("Edgeville Home Teleport", InterfaceID.MagicSpellbook.TELEPORT_HOME_ZAROS, -1, -1),
    LUNAR_HOME_TELEPORT("Lunar Home Teleport", InterfaceID.MagicSpellbook.TELEPORT_HOME_LUNAR, -1, -1);


    private String name;
    private int packedID;
    private int unlockedSpriteID;
    private int lockedSpriteID;

    ChronoSpell(String name, int packedID, int unlockedSpriteID, int lockedSpriteID) {
        this.name = name;
        this.packedID = packedID;
        this.lockedSpriteID = lockedSpriteID;
        this.unlockedSpriteID = unlockedSpriteID;
    }
}
